
[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
blocs = "C4MgCjSCzHPnxaFHqTPFH7ur67rKHeunEQAzGRSMDKDM"

[programs.devnet]
blocs = "C4MgCjSCzHPnxaFHqTPFH7ur67rKHeunEQAzGRSMDKDM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
bind_address = "127.0.0.1"
rpc_port = 18899
faucet_port = 19900
ledger = ".anchor/test-ledger-blocs"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "yarn run ts-node scripts/init.ts"
